[package]
edition = "2021"
name = "bevy-test"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = {version = "0.5.0"}
bevy_prototype_lyon = {version = "0.3.1"}

[toolchain]
channel = "nightly"
